AGM/AGM/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AGM.DAL;
using AGM.DAL.Security;
using AGM.Models;
using AGM.Repositories;

namespace AGM.Controllers
{
    [CustomAuthorize(Roles = "Admin", NotifyUrl = "/UnauthorizedPage")]
    public class PhotoController : Controller
    {
       private DataContext db = new DataContext();
        // POST: Accounts/Delete/5
     
        public async Task<ActionResult> DeleteImage(int id)
        {
            Models.Content content = await db.Contents.FindAsync(id);
            db.Contents.Remove(content);
            await db.SaveChangesAsync();
            return RedirectToAction("CreateImage");
        }

        //uploading images
        [Route("Index")]
        [HttpGet]
        public ActionResult ImageIndex()
        {
            System.Web.HttpContext.Current.Session["_SessionCompany"] = "Session works";
            var content = db.Contents.Select(s => new
            {
                s.ID,
                s.Title,
                s.Image,
                s.UserID
            });
            string name = User.Identity.Name;
            var user = db.Users.ToList().Where(a => a.Email == name);
            int? userid = 0;
            foreach (var row in user)
            {
                userid = row.UserId;
            }
            List<ContentViewModel> contentModel = content.Select(item => new ContentViewModel()
            {
                ID = item.ID,
                Title = item.Title,
                Image = item.Image,
               UserID = item.UserID

            }).Where(a => a.UserID == userid).ToList();
            if (contentModel.Count == 0)
            {
                return View("CreateImage");
            }
            else
            {
                return View(contentModel);
            }

        }

        /// <summary>
        /// Retrive Image from database 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public byte[] GetImageFromDataBase(int Id)
        {
            var q = from temp in db.Contents where temp.ID == Id select temp.Image;
            try
            {
                byte[] cover = q.First();
                return cover;
            }
            catch (Exception)
            {
                byte[] cover = null;
                return cover;
            }


        }

        [HttpGet]
        public ActionResult CreateImage()
        {
            string name = User.Identity.Name;
            var user = db.Users.ToList().Where(a => a.Email == name);
            int? userid = 0;
            int count = 0;
            foreach (var row in user)
            {
                userid = row.UserId;
            }
            try
            {
                var swazi = db.Contents.ToList().Where(a => a.UserID == userid);
                foreach (var row in swazi)
                {
                    count++;
                }
                if (count >= 1)
                {
                    return RedirectToAction("ImageIndex");
                }
            }
            catch (Exception e)
            {
                
            }
           
            return View();
        }
        /// <summary>
        /// Save content and images
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Route("CreateImage")]
        [HttpPost]
        public ActionResult CreateImage(ContentViewModel model)
        {
            string name = User.Identity.Name;
            var user = db.Users.ToList().Where(a => a.Email == name);
            int? userid = 0;
            foreach (var row in user)
            {
                userid = row.UserId;
            }
            HttpPostedFileBase file = Request.Files["ImageData"];
            ContentRepository service = new ContentRepository();
            int id = Convert.ToInt32(userid);
            int i = service.UploadImageInDataBase(file, model, id);
            if (i == 1)
            {
                return RedirectToAction("ImageIndex");
            }
            return View(model);
        }
    }
}

AGM/AGM/Views/Photo/CreateImage.cshtml
@model AGM.Models.ContentViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Admin.cshtml";
}

}

<script src="~/ckeditor/ckeditor.js"></script>
<script src="~/ckeditor/adapters/jquery.js"></script>
<section class="wrapper">
    <div class="row" id="myStruc">
        <div class="panel-heading" style="background-color: goldenrod">
            <h3 style="color: #428bca">Companies</h3>
        </div>
        <h4>Upload Profile Photo</h4>

        <script type="text/javascript">
            function fileCheck(obj) {
                var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
                if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
                    alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
                }
            }
        </script>

        @using (Html.BeginForm("CreateImage", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true)

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="col-md-10">
                            @{
                                List<SelectListItem> listItems2 = new List<SelectListItem>();

                                listItems2.Add(new SelectListItem
                                {
                                    Text = "Profile",
                                    Value = "Profile"
                                });


                            }

                            @Html.DropDownListFor(model => model.Title, listItems2, "", new { @class = "form-control", })

                            @Html.ValidationMessageFor(model => model.Title)
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" required="" />
                        @Html.ValidationMessageFor(model => model.Image)
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Upload" class="btn btn-info btn-lg" />
                    </div>
                </div>
            </div>
                                }
    </div>
    </section>

AGM/AGM/Views/Photo/ImageIndex.cshtml
@model IEnumerable<AGM.Models.ContentViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Admin.cshtml";
}
}

<section class="wrapper">
    <div class="row" id="myStruc">
        <div class="panel-heading" style="background-color: goldenrod">
            <h3 style="color: #428bca">Companies</h3>
        </div>
        <h4>Profile Status</h4>



        <br />
        <table class="table" style="width: 1200px;">
            <tr>
                <th>
                    <b>Title</b>
                </th>
                <th>
                    <b>Image</b>
                </th>
                <th>
                    <b>Account ID</b>
                </th>
                <th>
                    Status
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>

                    <td>
                        <img src="~/Photo/RetrieveImage/@item.ID" alt="" height=100 width=100 />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserID)
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "DeleteImage", new { id = item.ID }, new { onclick = "return confirm('Are you sure you want to add or remove photo?');" })
                    </td>
                </tr>
            }
        </table>
    </div>
    </section>