AGM/AGM/Models/Register.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AGM.Models
{
    public class Register
    {
        public int RegisterID { get; set; }
        //AGMID,COMPANY CODE
        public string memberno { get; set; }
        public string regstatus { get; set; }
        [Required]
        public string membertype { get; set; }
        [Required]
        [Display(Name = "Forenames")]
        public string forenames { get; set; }
        [Required]
        [Display(Name="Surname/Company")]
        public string surnamecompany { get; set; }
     public int Balance { get; set; }
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public DateTime DateAdded { get; set; }
        public int CompanyID { get; set; }
        public string address { get; set; }
        [ForeignKey("CompanyID")]
        public virtual Company Company { get; set; }
        public int AGMID { get; set; }
        [ForeignKey("AGMID")]
        public virtual AGM AGM { get; set; }
    }
}

AGM/AGM/Controllers/RegistersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Design.Serialization;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AGM.DAL;
using AGM.Models;
using PagedList;
using Database = WebMatrix.Data.Database;

namespace AGM.Controllers
{
    public class RegistersController : Controller
    {
        private DataContext db = new DataContext();
      public static string file = "";
        // GET: Registers
        public async Task<ActionResult> Index(string sortOrder, string currentFilter,string searchString, int? page)
        {
            var comp = db.Companys.ToList().Where(a => a.ActivationStatus == true);
            int? compID = 0;
            foreach (var row in comp)
            {
                System.Web.HttpContext.Current.Session["_CompanyName"] = row.CompanyName;
                compID = row.CompanyID;
            }
         
            var registers = db.Registers.Include(r => r.AGM).Include(r => r.Company).Where(a=>a.CompanyID==compID);
            if (!String.IsNullOrEmpty(searchString))
            {
                registers = registers.Where(s =>
                s.surnamecompany.ToUpper().Contains(searchString.ToUpper())
                ||
                s.surnamecompany.ToUpper().Contains(searchString.ToUpper()));
            }
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            switch (sortOrder)
            {
                case "name_desc":
                    registers = registers.OrderByDescending(s => s.surnamecompany);
                    break;
                case "Date":
                    registers = registers.OrderBy(s => s.DateAdded);
                    break;
                case "date_desc":
                    registers = registers.OrderByDescending(s => s.DateAdded);
                    break;
                default:
                    registers = registers.OrderBy(s => s.RegisterID);
                    break;
            }
            int pageSize =20;
            int pageNumber = (page ?? 1);
            return View(registers.ToPagedList(pageNumber, pageSize));
       }

        // GET: Registers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = await db.Registers.FindAsync(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            return View(register);
        }

      
        // GET: Registers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = await db.Registers.FindAsync(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            ViewBag.AGMID = new SelectList(db.AGMs, "AGMID", "AGMstatus", register.AGMID);
            ViewBag.CompanyID = new SelectList(db.Companys, "CompanyID", "CompanyCode", register.CompanyID);
            return View(register);
        }

        // POST: Registers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "RegisterID,memberno,regstatus,membertype,forenames,surnamecompany,Balance,DateAdded,CompanyID,AGMID,address")] Register register)
        {
            if (ModelState.IsValid)
            {
                db.Entry(register).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AGMID = new SelectList(db.AGMs, "AGMID", "AGMstatus", register.AGMID);
            ViewBag.CompanyID = new SelectList(db.Companys, "CompanyID", "CompanyCode", register.CompanyID);
            return View(register);
        }

        // GET: Registers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = await db.Registers.FindAsync(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            return View(register);
        }

        // POST: Registers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Register register = await db.Registers.FindAsync(id);
            db.Registers.Remove(register);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public string CreateRandomPassword(int size)
        {
            string allowedChars = "";
            allowedChars += "1,2,3,4,5,6,7,8,9,0";
            char[] sep = { ',' };
            string[] arr = allowedChars.Split(sep);
            string passwordString = "";
            string password = "";
            string temp = "";
            Random rand = new Random();
            for (int i = 0; i < size; i++)
            {
                temp = arr[rand.Next(0, arr.Length)];
                passwordString += temp;
            }
            password = passwordString;
            return password;
        }
        public ActionResult Importexcel()
        {

            return View();

        }

        [HttpPost]
        public ActionResult Importexcel(HttpPostedFileBase file)
        {

            if (Request.Files["FileUpload"].ContentLength > 0)
            {
                string fileExtension =
                                     System.IO.Path.GetExtension(Request.Files["FileUpload"].FileName);

                if (fileExtension == ".xls" || fileExtension == ".xlsx")
                {

                    // Create a folder in App_Data named ExcelFiles because you need to save the file temporarily location and getting data from there. 
                    string fileLocation = Server.MapPath("~/App_Data/ExcelFiles/" + Request.Files["FileUpload"].FileName);
                  
                    if (System.IO.File.Exists(fileLocation))
                        System.IO.File.Delete(fileLocation);

                    Request.Files["FileUpload"].SaveAs(fileLocation);
                    string excelConnectionString = string.Empty;

                    excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + fileLocation +
                                            ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                    //connection String for xls file format.
                    if (fileExtension == ".xls")
                    {
                        excelConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + fileLocation +
                                                ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";
                    }
                    //connection String for xlsx file format.
                    else if (fileExtension == ".xlsx")
                    {

                        excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + fileLocation +
                                                ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                    }



                    //Create Connection to Excel work book and add oledb namespace
                    OleDbConnection excelConnection = new OleDbConnection(excelConnectionString);
                    excelConnection.Open();
                    DataTable dt = new DataTable();

                    dt = excelConnection.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                    if (dt == null)
                    {
                        return null;
                    }

                    String[] excelSheets = new String[dt.Rows.Count];
                    int t = 0;
                    //excel data saves in temp file here.
                    foreach (DataRow row in dt.Rows)
                    {
                        excelSheets[t] = row["TABLE_NAME"].ToString();
                        t++;
                    }
                    OleDbConnection excelConnection1 = new OleDbConnection(excelConnectionString);
                    DataSet ds = new DataSet();

                    string query = string.Format("Select * from [{0}]", excelSheets[1]);
                    using (OleDbDataAdapter dataAdapter = new OleDbDataAdapter(query, excelConnection1))
                    {
                        dataAdapter.Fill(ds);
                    }
                    int id = Convert.ToInt32(System.Web.HttpContext.Current.Session["_CompanyRegID"].ToString());
                    int id2 = Convert.ToInt32(System.Web.HttpContext.Current.Session["_AGMID"].ToString());

                    for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                    {

AGM/AGM/Views/Registers/Delete.cshtml
@model AGM.Models.Register

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<section class="wrapper">
    <div class="row" id="myStruc">
        <div class="panel-heading" style="background-color: goldenrod">
            <h3 style="color: #428bca">Registers</h3>
        </div>
        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Register</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.AGM.AGMstatus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AGM.AGMstatus)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Company.CompanyCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Company.CompanyCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.memberno)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.memberno)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.regstatus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.regstatus)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.membertype)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.membertype)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.forenames)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.forenames)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.surnamecompany)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.surnamecompany)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Balance)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Balance)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateAdded)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateAdded)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</section>

AGM/AGM/Views/Registers/Details.cshtml
@model AGM.Models.Register

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<section class="wrapper">
    <div class="row" id="myStruc">
        <div class="panel-heading" style="background-color: goldenrod">
            <h3 style="color: #428bca">Registers</h3>
        </div>
        <h2>Details</h2>

        <div>
            <h4>Register</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.AGM.AGMstatus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AGM.AGMstatus)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Company.CompanyCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Company.CompanyCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.memberno)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.memberno)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.regstatus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.regstatus)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.membertype)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.membertype)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.forenames)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.forenames)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.surnamecompany)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.surnamecompany)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Balance)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Balance)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateAdded)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateAdded)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.RegisterID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</section>

AGM/AGM/Views/Registers/Edit.cshtml
@model AGM.Models.Register

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<section class="wrapper">
    <div class="row" id="myStruc">
        <div class="panel-heading" style="background-color: goldenrod">
            <h3 style="color: #428bca">Registers</h3>
        </div>
        <h2>Edit</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Register</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.RegisterID)
                <table class="table table-responsive">

                    <tr>
                        <td>
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.regstatus, htmlAttributes: new { @class = "control-label col-md-2" })
                                </div>
                                <div class="col-md-10">
                                    @{
                                        List<SelectListItem> listItems = new List<SelectListItem>();
                                        listItems.Add(new SelectListItem
                                        {
                                            Text = "Activate",
                                            Value = "Activate"
                                        });
                                        listItems.Add(new SelectListItem
                                        {
                                            Text = "Deactivate",
                                            Value = "Deactivate",
                                            Selected = true
                                        });

                                    }

                                    @Html.DropDownListFor(model => model.regstatus, listItems, "", new {@class = "form-control"})
                                    @Html.ValidationMessageFor(model => model.regstatus, "", new {@class = "text-danger"})
                                </div>
                            </div>

                        </td>
                        <td>
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.membertype, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>
                                    <div class="col-md-10">
                                        @{
                                            List<SelectListItem> listItems2 = new List<SelectListItem>();
                                            listItems2.Add(new SelectListItem
                                            {
                                                Text = "Physical",
                                                Value = "Physical"
                                            });
                                            listItems2.Add(new SelectListItem
                                            {
                                                Text = "Proxy",
                                                Value = "Proxy",
                                                Selected = true
                                            });

                                        }

                                        @Html.DropDownListFor(model => model.membertype, listItems2, "", new { @class = "form-control", })
                                        @Html.ValidationMessageFor(model => model.membertype, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.forenames, htmlAttributes: new {@class = "control-label col-md-2"})
                                </div>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.forenames, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.forenames, "", new {@class = "text-danger"})
                                </div>
                            </div>
                        </td>
                        
                    </tr>
                    <tr>
                        <td>
                            <div class="form-group" style="visibility:hidden">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.AGMID, htmlAttributes: new { @class = "control-label col-md-2" })
                                </div>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.AGMID, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.AGMID, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </td>
                        <td>
                            <div class="form-group" style="visibility: hidden">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.CompanyID, htmlAttributes: new {@class = "control-label col-md-2"})
                                </div>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CompanyID, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.CompanyID, "", new {@class = "text-danger"})
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group" style="visibility:hidden">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.memberno, htmlAttributes: new { @class = "control-label col-md-2" })
                                </div>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.memberno, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.memberno, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.surnamecompany, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.surnamecompany, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.surnamecompany, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                        </td>


                        <td>
                            <div class="form-group">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
                                   </div>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                        </td><td>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-info" id="btn" />
        </div>
    </div>
</td>
                        <td>
                            <div class="form-group" style="visibility:hidden">
                                @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.JQueryUI().DatepickerFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } }).ShowButtonPanel(true).ChangeYear(true).ChangeMonth(true)

                                  @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                 
                  
                    </tr>


                </table>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</section>

AGM/AGM/Views/Registers/Importexcel.cshtml
@{
    ViewBag.Title = "Importexcel";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<section class="wrapper">
    <div class="row" id="myStruc">
        <div class="panel-heading" style="background-color: goldenrod">
            <h3 style="color: #428bca">Registers</h3>
        </div>
        <h2>Importexcel</h2>
        <p>
            @Html.ActionLink("Register Index", "Index")
        </p>
        @using (Html.BeginForm("Importexcel", "Registers", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div>

                <input type="file" id="FileUpload"
                       name="FileUpload" required data-val="true" data-val-required="please select a file" />

                <input type="submit" id="Submit" class="submit" value="Upload" title="Click to upload file" />

            </div>
        }
    </div>
</section>

AGM/AGM/Views/Registers/Index.cshtml
@model PagedList.IPagedList<AGM.Models.Register>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<section class="wrapper">
    <div class="row" id="myStruc">
        <div class="panel-heading" style="background-color: goldenrod">
            <h3 style="color: #428bca">Registers</h3>
        </div>
        <h2>Index</h2>
        <h4>Company Name: @HttpContext.Current.Session["_CompanyName"].ToString()</h4>
    <h4> Company ID: @HttpContext.Current.Session["_CompanyRegID"].ToString()</h4>
    <h4>AGMID:@HttpContext.Current.Session["_AGMID"].ToString()</h4>


    <p>
        @Html.ActionLink("Upload Register", "ImportExcel")
    </p>
        @using (Html.BeginForm("Index", "Registers", FormMethod.Get))
        {
            <p>
                Find by name: @Html.TextBox("SearchString",ViewBag.CurrentFilter as
string)
                <input type="submit" value="Search" />
            </p>
        }
        <table class="table table-striped">
            <tr>
                <th>
                  AGMstatus
                </th>
                <th>
                CompanyCode
                </th>
                <th>
                  Member No
                </th>
                <th>
               Reg Status
                </th>
                <th>
                Member Type
                </th>
                <th>
                 Forenames
                </th>
                <th>
                    @Html.ActionLink("Surname Company", "Index", new{sortOrder =ViewBag.NameSortParm})
               </th>
                <th>
                   Balance
                </th>
                <th>
                    @Html.ActionLink("Date Added", "Index", new {sortOrder=ViewBag.DateSortParm})
                    
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AGM.AGMstatus)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Company.CompanyCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.memberno)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.regstatus)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.membertype)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.forenames)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.surnamecompany)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Balance)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateAdded)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.RegisterID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.RegisterID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.RegisterID })
                    </td>
                </tr>
            }

        </table>
        <br />
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
        @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index",
new
{
    page,
    sortOrder = ViewBag.CurrentSort,
    currentFilter =
ViewBag.CurrentFilter
}))